import React from "react";
import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";

export type ComplianceReportProps = {
  filename?: string;
  generatedOn?: string; // e.g. '01 Nov 2025, 14:43 SGT'
  generatedBy?: string; // e.g. 'Agentic AML System'
  logoDataUri?: string;
  // Documents: list of uploaded docs with name and timestamp
  documents?: Array<{ id: string; filename: string; uploadedAt: string }>;
  // Overall assessment provided by AI agent (mock for now)
  overallRisk?: string;
  overallSummary?: string;
  // Per-document assessments: id, riskLevel, summary
  assessments?: Array<{ id: string; riskLevel: string; summary: string }>;
};

const COLORS = {
  body: "#1A1A1A",
  header: "#1976D2",
  lightGray: "#F2F2F2",
};

const styles = StyleSheet.create({
  page: {
    paddingTop: 72,
    paddingBottom: 56,
    paddingHorizontal: 72, // ~1 inch margins on A4
    fontFamily: "Helvetica",
    color: COLORS.body,
    fontSize: 11,
  } as any,
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  } as any,
  logoBox: {
    width: 50,
    height: 50,
    backgroundColor: COLORS.lightGray,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  } as any,
  generatedBy: { fontSize: 9, color: "#555555" } as any,

  title: {
    textAlign: "center",
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.body,
    marginTop: 6,
  } as any,
  subtitle: { textAlign: "center", fontSize: 11, color: "#555555", marginTop: 4 } as any,

  listItem: { marginBottom: 6 } as any,
});

export default function ComplianceReport({
  filename = "Report",
  generatedOn = "",
  generatedBy = "",
  logoDataUri,
  documents = [],
  overallRisk = "",
  overallSummary = "",
  assessments = [],
}: ComplianceReportProps) {
  return (
    <Document>
      {/* Main page: document list + overall assessment */}
      <Page size="A4" style={styles.page} wrap>
        <View style={styles.headerRow} fixed>
          <View style={{ flexDirection: "row", alignItems: "center" }}>
            {typeof logoDataUri === "string" && logoDataUri ? (
              <Image src={logoDataUri} style={{ width: 50, height: 50, marginRight: 8 }} />
            ) : (
              <View style={styles.logoBox}>
                <Text style={{ fontSize: 10, color: COLORS.body }}>COMPANY</Text>
              </View>
            )}
          </View>

          <View>
            <Text style={{ fontSize: 9, textAlign: "right", color: "#555555" }}>
              Generated by {generatedBy || "Agentic AML System"}
            </Text>
            <Text style={{ fontSize: 9, textAlign: "right", color: "#555555" }}>
              {generatedOn ? `Generated on: ${generatedOn}` : ""}
            </Text>
          </View>
        </View>

        <Text style={styles.title}>{filename}</Text>

        <View style={{ marginTop: 18 }}>
          <Text style={{ fontSize: 12, fontWeight: "bold", marginBottom: 6 }}>
            Uploaded documents
          </Text>
          {documents.length === 0 && <Text>-</Text>}
          {documents.map((d, i) => (
            <View key={d.id} style={{ marginBottom: 6 }}>
              <Text style={{ fontSize: 11 }}>
                {i + 1}. {d.filename}
              </Text>
              <Text style={{ fontSize: 9, color: "#555" }}>Uploaded at: {d.uploadedAt}</Text>
            </View>
          ))}
        </View>

        <View style={{ marginTop: 18 }}>
          <Text style={{ fontSize: 12, fontWeight: "bold", marginBottom: 6 }}>
            Overall Risk Assessment
          </Text>
          <Text style={{ fontSize: 11, marginBottom: 8 }}>Risk level: {overallRisk || "-"}</Text>
          <Text style={{ fontSize: 11 }}>{overallSummary || "-"}</Text>
        </View>
      </Page>

      {/* Per-document pages */}
      {documents.map((d) => {
        const ass = assessments.find((a) => a.id === d.id) || { riskLevel: "-", summary: "-" };
        return (
          <Page key={d.id} size="A4" style={styles.page} wrap>
            <View style={styles.headerRow} fixed>
              <View style={{ flexDirection: "row", alignItems: "center" }}>
                {typeof logoDataUri === "string" && logoDataUri ? (
                  <Image src={logoDataUri} style={{ width: 50, height: 50, marginRight: 8 }} />
                ) : (
                  <View style={styles.logoBox}>
                    <Text style={{ fontSize: 10, color: COLORS.body }}>COMPANY</Text>
                  </View>
                )}
              </View>

              <View>
                <Text style={{ fontSize: 9, textAlign: "right", color: "#555555" }}>
                  {generatedBy || "Agentic AML System"}
                </Text>
                <Text style={{ fontSize: 9, textAlign: "right", color: "#555555" }}>
                  {generatedOn ? `Generated on: ${generatedOn}` : ""}
                </Text>
              </View>
            </View>

            <Text style={{ fontSize: 16, fontWeight: "bold", marginTop: 6 }}>{d.filename}</Text>
            <Text style={{ fontSize: 10, color: "#555", marginBottom: 12 }}>
              Uploaded at: {d.uploadedAt}
            </Text>

            <View>
              <Text style={{ fontSize: 12, fontWeight: "bold", marginBottom: 6 }}>Risk level</Text>
              <Text style={{ fontSize: 14, marginBottom: 12 }}>{ass.riskLevel}</Text>

              <Text style={{ fontSize: 12, fontWeight: "bold", marginBottom: 6 }}>
                Assessment summary
              </Text>
              <Text style={{ fontSize: 11 }}>{ass.summary}</Text>
            </View>
          </Page>
        );
      })}
    </Document>
  );
}
